name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: python -m pip install --upgrade pip poetry

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Lint with Ruff
        run: |
          python -m poetry run ruff check .

      - name: Format check (Black)
        run: |
          python -m poetry run black --check .

      - name: Import sorting (isort)
        run: |
          python -m poetry run isort --check-only .

      - name: Type-check (Mypy)
        run: |
          python -m poetry run mypy .

      - name: Run tests & coverage
        run: |
          python -m poetry run pytest --cov=orchestrator --cov-fail-under=100

      - name: Container security scan
        uses: aquasecurity/trivy-action@0.32.0

