name: Institutional Python CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Black (format check)
      run: black --check .

    - name: Run Flake8 (lint)
      run: flake8 .

    - name: Run isort (import order)
      run: isort . --check-only

    - name: Run mypy (static type check)
      run: mypy .

    - name: Run Pytest (unit/integration tests)
      run: pytest -q --tb=short --disable-warnings

    - name: Log Governance Artefact ID
      run: echo "Governance Artefact ID: GA-20250728-04"
