# AetherMind™ Platinum CI Workflow
# File: .github/workflows/python-ci.yml
# Organs: 🧠 Brain, Compliance Pipeline
# Artefact ID: GA-20250801-22
# Compliance: v3.0, Stepwise Ops Protocol

name: Platinum Python CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pip & wheel
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pre-commit black isort flake8 mypy

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Run unit tests
        run: python -m pytest -q --tb=short --disable-warnings
